### ISSUE TITLE
 "sbt/sbt run" encounter error

### ISSUE THREAD

**Issue by luckypoem** [georgeOsdDev/jekytrum#6]
hello.

root@AR:/usr/local/jekytrum-site# sbt/sbt run

it shows:
...
[error] (*:update) sbt.ResolveException: unresolved dependency: tv.cntt#xitrum_2.11;3.19-SNAPSHOT: not found
[error] unresolved dependency: tv.cntt#xitrum-scalate_2.11;2.3-SNAPSHOT: not found
[error] Total time: 399 s, completed 2016-11-23 8:52:44
root@AR:/usr/local/jekytrum-site#

hwo to fix it?
thank u

**Comment by georgeOsdDev** [comment]
Please try remove `-SNAPSHOT`.

BTW:
Latest Xitrum version is 3.28.1
https://groups.google.com/forum/#!topic/xitrum-framework/9db9LcOljow

You can reference latest empty skeleton of Xitrum from https://github.com/xitrum-framework/xitrum-new
and  Xitrum-Guide(http://xitrum-framework.github.io/guide.html)

This project is experimental.
I do not intend to update this repository sorry.
